# Generated by Django 5.0.6 on 2026-07-15 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Failed Login'), ('PRODUCT_ADDED', 'Product Added'), ('PRODUCT_EDITED', 'Product Edited'), ('PRODUCT_DELETED', 'Product Deleted'), ('INVENTORY_UPDATED', 'inventory Updated'), ('SALE_COMPLETED', 'Sale Completed'), ('CUSTOMER_PAYMENT', 'Customer Payment'), ('PRICE_CHANGED', 'Price Changed'), ('USER_MANAGEMENT', 'User Management'), ('OTHER', 'Other')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('target_repr', models.CharField(blank=True, help_text='String representation of the affected object', max_length=255)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx')],
            },
        ),
    ]
