# Generated by Django 5.0.6 on 2026-07-15 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meat_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('meat_type', models.CharField(choices=[('PORK', 'Pork'), ('BEEF', 'Beef'), ('CHICKEN', 'Chicken'), ('GOAT', 'Goat Meat'), ('OTHER', 'Other')], max_length=10)),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Weight received in this batch (kg).', max_digits=10)),
                ('remaining_stock_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meat_supplies', to='suppliers.supplier')),
            ],
            options={
                'verbose_name_plural': 'Meat inventory',
                'ordering': ['meat_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeatTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RECEIVE', 'Stock Received'), ('SALE', 'Sale Deduction'), ('ADJUST', 'Adjustment'), ('WASTE', 'Wastage / Spoilage')], max_length=10)),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Signed: positive=in, negative=out', max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='meat.meatinventory')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='meatinventory',
            index=models.Index(fields=['meat_type'], name='meat_meatin_meat_ty_70b14d_idx'),
        ),
        migrations.AddIndex(
            model_name='meatinventory',
            index=models.Index(fields=['expiration_date'], name='meat_meatin_expirat_804014_idx'),
        ),
    ]
