# Generated by Django 5.0.6 on 2026-07-15 00:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '__first__'),
        ('meat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('uuid_ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Store Credit (Customer Debt)')], default='CASH', max_length=10)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partially Paid'), ('UNPAID', 'Unpaid')], default='PAID', max_length=10)),
                ('amount_tendered', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('change_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_made', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product (canned/dry goods)'), ('MEAT', 'Fresh Meat')], max_length=10)),
                ('description', models.CharField(help_text='Snapshot of product/meat name at time of sale', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Units for products, kg for meat', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('meat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='meat.meatinventory')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at'], name='sales_sale_created_e208b3_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_status'], name='sales_sale_payment_f41ab8_idx'),
        ),
    ]
